version: '3'

services:
  stablediffusion:
    container_name: stablediffusion
    image: sharrnah/stable-diffusion-guitard
    ports:
      - 7860:8080
    stdin_open: true
    tty: true
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./.cache/:/.cache/
      # mounting model files as read-only
      - ./models/:/models/:ro
      # generated outputs mount
      - ./outputs/:/outputs/
