version: '3'

services:
  stablediffusion:
    container_name: stablediffusion
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUN_MODE
    ports:
      - 7860:8080
    stdin_open: true
    tty: true
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      # mount cache dirs
      - ./.cache/app:/root/.cache
      - ./.cache/facexlib/:/opt/conda/envs/ldm/lib/python3.8/site-packages/facexlib/weights/
      # mounting model files
      - ./models/:/models/
      # generated outputs mount
      - ./outputs/:/outputs/
