version: '3'

services:
  stablediffusion:
    container_name: stablediffusion
    image: sharrnah/stable-diffusion-guitard
    environment:
      - RUN_MODE
      - WEBUI_RELAUNCH=true
      - ENABLE_TEXTUAL_INVERSION
    ports:
      - 7860:8080
    stdin_open: true
    tty: true
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      # mount cache dirs
      - ./.cache/app:/root/.cache
      - ./.cache/facexlib/:/app/src/facexlib/facexlib/weights/
      - ./.cache/gfpgan/:/app/gfpgan/weights/
      # mounting model files
      - ./models/:/models/
      # generated outputs mount
      - ./outputs/:/outputs/
